import type { WhoisInfo } from 'src/interfaces';
import { WhoisInfoStatus } from 'src/interfaces';
import { fmtDate } from 'src/utils/utils';

export interface DomainChar {
  title: string;
  chars: string[];
}
export const DomainChars: DomainChar[] = [
  {
    title: '数字',
    chars: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
  },
  {
    title: '数字无04',
    chars: ['1', '2', '3', '5', '6', '7', '8', '9'],
  },
  {
    title: '字母',
    chars: [
      'a',
      'b',
      'c',
      'd',
      'e',
      'f',
      'g',
      'h',
      'i',
      'j',
      'k',
      'l',
      'm',
      'n',
      'o',
      'p',
      'q',
      'r',
      's',
      't',
      'u',
      'v',
      'w',
      'x',
      'y',
      'z',
    ],
  },
  {
    title: '声母',
    chars: [
      'b',
      'c',
      'd',
      'f',
      'g',
      'h',
      'j',
      'k',
      'l',
      'm',
      'n',
      'p',
      'q',
      'r',
      's',
      't',
      'w',
      'x',
      'y',
      'z',
    ],
  },
  {
    title: '非声母',
    chars: ['a', 'e', 'i', 'o', 'u', 'v'],
  },
  {
    title: '单拼',
    chars: [
      'ai',
      'an',
      'ba',
      'ca',
      'ce',
      'da',
      'de',
      'di',
      'ei',
      'en',
      'fa',
      'ge',
      'he',
      'ji',
      'ka',
      'ke',
      'la',
      'le',
      'li',
      'na',
      'ne',
      'pa',
      'pi',
      'qi',
      're',
      'ri',
      'sa',
      'se',
      'ta',
      'te',
      'ti',
      'wa',
      'xi',
      'ya',
      'ye',
      'yi',
      'za',
      'ze',
      'ao',
      'bi',
      'bo',
      'bu',
      'ci',
      'cu',
      'du',
      'er',
      'fo',
      'fu',
      'gu',
      'hu',
      'ju',
      'ku',
      'lo',
      'lu',
      'lv',
      'mi',
      'mo',
      'mu',
      'nu',
      'nv',
      'ou',
      'po',
      'pu',
      'qu',
      'ru',
      'si',
      'su',
      'tu',
      'wo',
      'wu',
      'xu',
      'yo',
      'yu',
      'zi',
      'zu',
      'bai',
      'ban',
      'bao',
      'bei',
      'ben',
      'cai',
      'can',
      'cao',
      'cen',
      'cha',
      'che',
      'chi',
      'dai',
      'dan',
      'dao',
      'dei',
      'den',
      'dia',
      'fan',
      'fei',
      'fen',
      'gai',
      'gan',
      'gao',
      'gei',
      'gen',
      'hai',
      'han',
      'hao',
      'hei',
      'hen',
      'jia',
      'jie',
      'jin',
      'kai',
      'kan',
      'kao',
      'kei',
      'ken',
      'lai',
      'lan',
      'lao',
      'lei',
      'lia',
      'mai',
      'man',
      'mao',
      'mei',
      'men',
      'nai',
      'nan',
      'nao',
      'nei',
      'nen',
      'pai',
      'pan',
      'pao',
      'pei',
      'pen',
      'qia',
      'qie',
      'qin',
      'ran',
      'rao',
      'ren',
      'sai',
      'san',
      'sao',
      'sen',
      'sha',
      'she',
      'shi',
      'tai',
      'tan',
      'tao',
      'wai',
      'wan',
      'wei',
      'xia',
      'xie',
      'xin',
      'yan',
      'yao',
      'yin',
      'zai',
      'zan',
      'zao',
      'zei',
      'zen',
      'zha',
      'zhe',
      'zhi',
      'ang',
      'bie',
      'bin',
      'chu',
      'cou',
      'cui',
      'cun',
      'cuo',
      'die',
      'diu',
      'dou',
      'dui',
      'dun',
      'duo',
      'eng',
      'fou',
      'gou',
      'gua',
      'gui',
      'gun',
      'guo',
      'hou',
      'hua',
      'hui',
      'hun',
      'huo',
      'jiu',
      'jue',
      'jun',
      'kou',
      'kua',
      'kui',
      'kun',
      'kuo',
      'lie',
      'lin',
      'liu',
      'lou',
      'lue',
      'lun',
      'luo',
      'mie',
      'min',
      'miu',
      'mou',
      'nie',
      'nin',
      'niu',
      'nou',
      'nue',
      'nun',
      'nuo',
      'pie',
      'pin',
      'pou',
      'qiu',
      'que',
      'qun',
      'rou',
      'rui',
      'run',
      'ruo',
      'shu',
      'sou',
      'sui',
      'sun',
      'suo',
      'tie',
      'tou',
      'tui',
      'tun',
      'tuo',
      'wen',
      'xiu',
      'xue',
      'xun',
      'you',
      'yue',
      'yun',
      'zhu',
      'zou',
      'zui',
      'zun',
      'zuo',
      'lve',
      'lue',
      'nve',
      'nue',
      'bang',
      'beng',
      'cang',
      'chai',
      'dang',
      'deng',
      'dian',
      'fang',
      'gang',
      'geng',
      'gong',
      'hang',
      'heng',
      'jian',
      'jiao',
      'kang',
      'keng',
      'kong',
      'lang',
      'lian',
      'liao',
      'mang',
      'meng',
      'nang',
      'neng',
      'nian',
      'pang',
      'peng',
      'qian',
      'qiao',
      'rang',
      'reng',
      'rong',
      'sang',
      'seng',
      'shai',
      'shan',
      'shao',
      'shei',
      'shen',
      'tang',
      'teng',
      'tian',
      'wang',
      'xian',
      'xiao',
      'yang',
      'ying',
      'zang',
      'zeng',
      'zhai',
      'zhan',
      'zhao',
      'zhei',
      'zhen',
      'bian',
      'biao',
      'bing',
      'chou',
      'chua',
      'chui',
      'chun',
      'chuo',
      'cong',
      'cuan',
      'diao',
      'ding',
      'dong',
      'duan',
      'feng',
      'guai',
      'guan',
      'hong',
      'huai',
      'huan',
      'jing',
      'juan',
      'kuai',
      'kuan',
      'ling',
      'long',
      'luan',
      'mian',
      'miao',
      'ming',
      'niao',
      'ning',
      'nong',
      'nuan',
      'pian',
      'piao',
      'ping',
      'qing',
      'quan',
      'ruan',
      'shou',
      'shua',
      'shui',
      'shun',
      'shuo',
      'song',
      'suan',
      'tiao',
      'ting',
      'tong',
      'tuan',
      'weng',
      'xing',
      'xuan',
      'yong',
      'yuan',
      'zhou',
      'zhua',
      'zhui',
      'zhun',
      'zhuo',
      'zong',
      'zuan',
      'chang',
      'cheng',
      'jiang',
      'liang',
      'niang',
      'qiang',
      'shang',
      'sheng',
      'xiang',
      'zhang',
      'zheng',
      'chong',
      'chuang',
      'guang',
      'huang',
      'jiong',
      'kuang',
      'qiong',
      'shuai',
      'shuan',
      'shuang',
      'xiong',
      'zhong',
      'zhuai',
      'zhuan',
      'zhuang',
    ],
  },
  {
    title: '2字符单拼',
    chars: ['a', 'e', 'i', 'o', 'u', 'v'],
  },
  {
    title: '3字符单拼',
    chars: [
      'bai',
      'ban',
      'bao',
      'bei',
      'ben',
      'cai',
      'can',
      'cao',
      'cen',
      'cha',
      'che',
      'chi',
      'dai',
      'dan',
      'dao',
      'dei',
      'den',
      'dia',
      'fan',
      'fei',
      'fen',
      'gai',
      'gan',
      'gao',
      'gei',
      'gen',
      'hai',
      'han',
      'hao',
      'hei',
      'hen',
      'jia',
      'jie',
      'jin',
      'kai',
      'kan',
      'kao',
      'kei',
      'ken',
      'lai',
      'lan',
      'lao',
      'lei',
      'lia',
      'mai',
      'man',
      'mao',
      'mei',
      'men',
      'nai',
      'nan',
      'nao',
      'nei',
      'nen',
      'pai',
      'pan',
      'pao',
      'pei',
      'pen',
      'qia',
      'qie',
      'qin',
      'ran',
      'rao',
      'ren',
      'sai',
      'san',
      'sao',
      'sen',
      'sha',
      'she',
      'shi',
      'tai',
      'tan',
      'tao',
      'wai',
      'wan',
      'wei',
      'xia',
      'xie',
      'xin',
      'yan',
      'yao',
      'yin',
      'zai',
      'zan',
      'zao',
      'zei',
      'zen',
      'zha',
      'zhe',
      'zhi',
      'ang',
      'bie',
      'bin',
      'chu',
      'cou',
      'cui',
      'cun',
      'cuo',
      'die',
      'diu',
      'dou',
      'dui',
      'dun',
      'duo',
      'eng',
      'fou',
      'gou',
      'gua',
      'gui',
      'gun',
      'guo',
      'hou',
      'hua',
      'hui',
      'hun',
      'huo',
      'jiu',
      'jue',
      'jun',
      'kou',
      'kua',
      'kui',
      'kun',
      'kuo',
      'lie',
      'lin',
      'liu',
      'lou',
      'lue',
      'lun',
      'luo',
      'mie',
      'min',
      'miu',
      'mou',
      'nie',
      'nin',
      'niu',
      'nou',
      'nue',
      'nun',
      'nuo',
      'pie',
      'pin',
      'pou',
      'qiu',
      'que',
      'qun',
      'rou',
      'rui',
      'run',
      'ruo',
      'shu',
      'sou',
      'sui',
      'sun',
      'suo',
      'tie',
      'tou',
      'tui',
      'tun',
      'tuo',
      'wen',
      'xiu',
      'xue',
      'xun',
      'you',
      'yue',
      'yun',
      'zhu',
      'zou',
      'zui',
      'zun',
      'zuo',
      'lve',
      'lue',
      'nve',
      'nue',
    ],
  },
  {
    title: '4字符单拼',
    chars: [
      'bang',
      'beng',
      'cang',
      'chai',
      'dang',
      'deng',
      'dian',
      'fang',
      'gang',
      'geng',
      'gong',
      'hang',
      'heng',
      'jian',
      'jiao',
      'kang',
      'keng',
      'kong',
      'lang',
      'lian',
      'liao',
      'mang',
      'meng',
      'nang',
      'neng',
      'nian',
      'pang',
      'peng',
      'qian',
      'qiao',
      'rang',
      'reng',
      'rong',
      'sang',
      'seng',
      'shai',
      'shan',
      'shao',
      'shei',
      'shen',
      'tang',
      'teng',
      'tian',
      'wang',
      'xian',
      'xiao',
      'yang',
      'ying',
      'zang',
      'zeng',
      'zhai',
      'zhan',
      'zhao',
      'zhei',
      'zhen',
      'bian',
      'biao',
      'bing',
      'chou',
      'chua',
      'chui',
      'chun',
      'chuo',
      'cong',
      'cuan',
      'diao',
      'ding',
      'dong',
      'duan',
      'feng',
      'guai',
      'guan',
      'hong',
      'huai',
      'huan',
      'jing',
      'juan',
      'kuai',
      'kuan',
      'ling',
      'long',
      'luan',
      'mian',
      'miao',
      'ming',
      'niao',
      'ning',
      'nong',
      'nuan',
      'pian',
      'piao',
      'ping',
      'qing',
      'quan',
      'ruan',
      'shou',
      'shua',
      'shui',
      'shun',
      'shuo',
      'song',
      'suan',
      'tiao',
      'ting',
      'tong',
      'tuan',
      'weng',
      'xing',
      'xuan',
      'yong',
      'yuan',
      'zhou',
      'zhua',
      'zhui',
      'zhun',
      'zhuo',
      'zong',
      'zuan',
    ],
  },
  {
    title: '5字符以上单拼',
    chars: [
      'chang',
      'cheng',
      'jiang',
      'liang',
      'niang',
      'qiang',
      'shang',
      'sheng',
      'xiang',
      'zhang',
      'zheng',
      'chong',
      'chuang',
      'guang',
      'huang',
      'jiong',
      'kuang',
      'qiong',
      'shuai',
      'shuan',
      'shuang',
      'xiong',
      'zhong',
      'zhuai',
      'zhuan',
      'zhuang',
    ],
  },
];

export const DomainStatus: Record<string, string> = {
  ok: '正常状态',
  inactive: '非激活状态',
  autoRenewPeriod: '自动续费',
  renewPeriod: '在续费中',
  clientDeleteProhibited: '禁止删除',
  serverDeleteProhibited: '禁止删除',
  clientUpdateProhibited: '禁止修改',
  serverUpdateProhibited: '禁止修改',
  pendingDelete: '正在删除',
  pendingTransfer: '正在转移',
  clientTransferProhibited: '禁止转移',
  serverTransferProhibited: '禁止转移',
  clientRenewProhibited: '禁止续费',
  serverRenewProhibited: '禁止续费',
  clientHold: '停止解析',
  serverHold: '停止解析',
  pendingVerification: '注册信息正在确认',
};

export const DomainSuffix: string[] = ['com', 'cn', 'app', 'dev', 'ai', 'io'];

export const parseDomainStr = (domainStr: string): string[] => {
  const spl = ',';
  domainStr = domainStr
    .replace(/[\r|\n| |，|;|；]+/g, ',')
    .replace(/^,+|,+$/g, '')
    .replace(/,{1,}/g, spl);
  const domains: string[] = [];
  const reg = /^([a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,10}/;
  domainStr.split(spl).forEach(function (value: string) {
    if (reg.test(value) && domains.indexOf(value) === -1) {
      domains.push(value);
    }
  });
  return domains;
};

export function createWhoisInfo(domain: string, data: any): WhoisInfo {
  const info: WhoisInfo = {
    domain: domain,
    status: WhoisInfoStatus.queryError,
    statusText: '',
    createTime: '',
    expireTime: '',
    updateTime: '',
    registerName: '', //注册商
    registerCountry: '', //注册国家
    registerStateProvince: '', //注册省
    dnsServer: '',
    concatPerson: '', //联系人
    concatEmail: '', //联系人
    raw: data,
    tryNum: 0,
    lastQueryTime: new Date().getTime(),
    fromCache: false,
  };
  if (!data) {
    return info;
  }
  if (!!data['creationDate'] || !!data['createdDate'] || !!data['registrationTime']) {
    info.status =WhoisInfoStatus.registered
    info.statusText = "已注册"
  } else {
    info.status = WhoisInfoStatus.unregistered
    info.statusText = "未注册"
  }
  //保留域名
  if (info.status == WhoisInfoStatus.unregistered) {
    if (data?.organisation == "Internet Assigned Numbers Authority") {
      info.status = WhoisInfoStatus.reserve
      info.statusText = "保留域名"
    }
  }
  info.raw = data;
  //获取被注册的信息
  if (info.status == WhoisInfoStatus.registered) {
    info.createTime = fmtDate(
      data['creationDate'] || data['createdDate'] || data['registrationTime'],
    );
    info.expireTime = fmtDate(
      data['registryExpiryDate'] ||
        data['registrarRegistrationExpirationDate'] ||
        data['expirationTime'] ||
        '',
    );
    info.dnsServer = data['nameServer'] || '';
    info.registerName = data['registrar'] || data['sponsoringRegistrar'] || '';
    info.registerCountry = data['registrantCountry'] || '';
    info.registerStateProvince = data['registrantStateProvince'] || '';
    info.concatPerson = data['adminName'] || data['registrant'] || data['adminOrganization'] || '';
    // info.statusText = this.getDomainStatus(data['domainStatus']);
    info.concatPerson =
      info.concatPerson == 'REDACTED FOR PRIVACY' && data['registrantOrganization']
        ? data['registrantOrganization']
        : info.concatPerson;
    info.concatEmail = data['registrantContactEmail'] || data['adminPhone'] || '';
  }
  return info;
}
